question_data = [{"category": "Geography", "type": "boolean", "difficulty": "medium",
                  "question": "Gothenburg is the capital of Sweden.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Computers", "type": "boolean",
                  "difficulty": "hard",
                  "question": "The IBM PC used an Intel 8008 microprocessor clocked at 4.77 MHz and 8 kilobytes of memory.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Japanese Anime & Manga",
                  "type": "boolean", "difficulty": "hard",
                  "question": "Druid is a mage class in &quot;Log Horizon&quot;.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Television", "type": "boolean",
                  "difficulty": "hard",
                  "question": "The Klingon home planet is Qo&#039;noS.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean",
                  "difficulty": "hard",
                  "question": "The weapon Clint Eastwood uses in &quot;Dirty Harry&quot; was a .44 Automag.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Science: Mathematics", "type": "boolean",
                  "difficulty": "hard",
                  "question": "L&#039;H&ocirc;pital was the mathematician who created the homonymous rule that uses derivatives to evaluate limits with indeterminations.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Japanese Anime & Manga",
                  "type": "boolean", "difficulty": "easy",
                  "question": "In Chobits, Hideki found Chii in his apartment.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Politics", "type": "boolean", "difficulty": "medium",
                  "question": "Jeb Bush was elected as Governor of Florida in 2002, starting his political career.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Music", "type": "boolean",
                  "difficulty": "easy",
                  "question": "Lead Singer Rivers Cuomo of American rock band Weezer attended Harvard.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Film", "type": "boolean",
                  "difficulty": "medium",
                  "question": "The original ending of Little Shop Of Horrors has the plants taking over the world.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
